TrainerConfig:

    num_of_epochs: 100

    checkpoint_interval: 2 # num of epochs

    log_interval: 100 # num of batches

    early_stopping_patience: 5 # num of epochs

    optimizer:
        name: Adam
        kwargs:
            lr: 0.00005
            weight_decay: 1.0e-05

    scheduler:
        name: reduce_on_plateau
        kwargs:
            mode: min
            factor: 0.5
            patience: 1
            threshold: 0.00001

    loss:
        name: FocalLoss
        kwargs:
            alpha: 1
            gamma: 2
