name: baikal25
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - h5py
  - pyyaml
  - matplotlib
  - jupyter
  - ipykernel
  - ipywidgets
  - pytest
  - root
  - pip
  - pip:
    - awkward
    - clearml