---
model_type: "encoder"
path_to_data: "/home2/ivkhar/Baikal/data/baikal_muatm-multi_0523_flat_norm.h5"
is_graph: False
model_params:
  in_features: 5
  hidden_size: 256
  num_layers: 5
  dim_feedforward_size: 256
  n_heads: 1
  out_size: 2
  dropout_p: 0.0
  use_bn: True
lr: 1.0e-5
batch_size: 128
num_train_steps_per_validation: 50
exp_name: "batchnorm_encoder_hs256_nl5_d256_nh1_bs128"
exp_project: "encoder_normalization_exp"
