---
model_type: "encoder"
train_type: "angle_reconstruction"
path_to_data: "/home/plotnikovgp/baikal/data/baikal_mc2020_multi_split_0924_MChits-8-2_normed.h5"
is_graph: False
model_params:
  in_features: 5
  hidden_size: 256
  num_layers: 5
  dim_feedforward_size: 256
  n_heads: 1
  out_size: 2
  dropout_p: 0.0
  use_cls_token: True
  return_only_cls_token: True
lr: 1.0e-4
batch_size: 128
num_train_steps_per_validation: 50
grad_clip_value: 1.0
exp_name: "encoder_nl5_hs256_nh1_bs128_loss-vec"
exp_project: "angle_reconstruction_v2_mc_0924"
