---
# 'acc': 0.9831503998694304, 'precision': 0.6802997858672377, 'recall': 0.3195212712461028,
model_type: "encoder"
train_type: "noise_sig"
path_to_data: "/home2/ivkhar/Baikal/data/normed/baikal_2020_sig-noise_mid-eq_normed.h5"
is_graph: False
model_params:
  in_features: 5
  hidden_size: 1024
  num_layers: 5
  dim_feedforward_size: 1024
  n_heads: 1
  out_size: 2
  dropout_p: 0.0
lr: 1.0e-4
batch_size: 128
num_train_steps_per_validation: 50
exp_name: "baseline_encoder_hs1024_nl5_nh1_bs128"
exp_project: "noise_sig_new_mc_0924"
