---
model_type: "graphnet"
train_type: "tres_and_track_cascade"
path_to_data: "/home/plotnikovgp/baikal/data/baikal_mc2020_multi_split_0924_MChits-8-2_normed.h5"
is_graph: True
knn_neighbours: 4
tres_cut: 10.0
model_params:
  knn_neighbours: 4
  in_features: 5
  out_size: 2
  second_head_out_size: 1
lr: 1.0e-3
batch_size: 128
num_train_steps_per_validation: 50
exp_name: "graphnet_k=0.001"
tres_mse_coef: 0.001
exp_project: "tres_and_track_cascade_mc_0924" 
