---
model_type: "graphnet"
train_type: "track_cascade"
path_to_data: "/home2/ivkhar/Baikal/data/normed/baikal_2020_sig-noise_mid-eq_normed.h5"
is_graph: True
knn_neighbours: 4
tres_cut: 10
model_params:
  knn_neighbours: 4
  in_features: 5
  out_size: 2
lr: 1.0e-3
batch_size: 128
num_train_steps_per_validation: 50
exp_name: "baseline_graphnet"
exp_project: "track_cascade_new_mc_0924"
