---
model_type: "graphnet"
train_type: "angle_reconstruction"
path_to_data: "/home/plotnikovgp/baikal/data/baikal_mc2020_multi_split_0924_MChits-8-2_normed.h5"
is_graph: True
knn_neighbours: 4
model_params:
  knn_neighbours: 4
  in_features: 5
  out_size: 3
  aggregate_output: True
lr: 1.0e-3
batch_size: 128
num_train_steps_per_validation: 50
grad_clip_value: 1.0
exp_name: "graphnet_loss-vec"
exp_project: "angle_reconstruction_v2_mc_0924"
