chunk_generator_cfg:
    chunk_size: 2
    processor_params:
        center_times: true
        calc_tres: false
        filter_cfg:
            only_signal: true
            min_hits: 5
            min_strings: 2
            min_Q: 0
            t_threshold: 100000.0
    fields: [PulsesAmpl, PulsesTime, Xrel, Yrel, Zrel, nu_induced]
    shuffle_paths: true

batch_size: 256

features_name: [PulsesAmpl, PulsesTime, Xrel, Yrel, Zrel]

labels_name: [nu_induced]

do_norm: true

norm_params:
    PulsesTime: [0.0, 238.5]
    PulsesAmpl: [6.8, 118.7]
    Xrel: [0.0, 60.0]
    Yrel: [0.0, 60.0]
    Zrel: [0.0, 260.0]

do_augment: true

augment_parmas:
    PulsesTime: 5.0
    PulsesAmpl: 0.1
    Xrel: 2.0
    Yrel: 2.0
    Zrel: 5.0

shuffle: true
