"""SUPERSEDED (2026-08-21) by data_manager/energy_truth/.

This script targets the old companion schema (targets/, interactions/, muon/), which no
longer exists: baikal_mc_merged_energy_truth.h5 was rebuilt with the schema documented in
doc/hdf5_energy_truth.md. Running it against the current file will not work.
"""
#!/usr/bin/env python3
"""Build the energy-truth companion to baikal_mc_merged.h5.

The main HDF5 is left untouched: HDF5 does not reclaim space when a group is deleted, so
adding an experimental branch to a multi-hundred-gigabyte file is a one-way operation. This
writes a separate file instead, in the same spirit as
`baikal_mc_merged_probs_*.h5`, which likewise carries its own copies of the keys needed to
use it standalone.

The artefact is deliberately **complete rather than opinionated**: it stores every quantity
from which any candidate energy target can be derived (see doc/mc_energy_truth.md §5), so the
choice of training target is made later and can be changed without recomputing anything.

Layout, mirroring the main file's grouping and its `mu_starts` indexing convention:

    {ptype}/
      ev_ids/{part}/data          (n_rows,)      S15   join key, copied so the file stands alone
      mu_starts/{part}/data       (n_rows+1,)    int64 row -> range of muons
      int_starts/{part}/data      (n_muons+1,)   int64 muon -> range of interactions
      interactions/{part}/data    (n_inter, 5)   f32   x, y, z (global m), energy (GeV), block
      muon/{part}/data            (n_muons, 8)   f32   theta, phi (deg), x, y, z, energy,
                                                       n_inter, e_ref_class
      targets/{part}/data         (n_muons, k)   f32   see TARGET_COLUMNS
      cluster/{part}/data         (n_rows,)      int16 cluster index of the row (ch // 288)

Rows are aligned one-to-one with the main file, including the duplication of multi-cluster
events; muon truth is duplicated with them exactly as `muons_prty` already does. Targets are
computed **per muon against the cluster of that row**, so a bundle yields one target row per
muon and no bundle-level convention has to be invented here.

Two guards run per part and abort the build on failure:
  * every muon's truth must reproduce `muons_prty/individ` (positions and energy exactly,
    angles to 1e-3 deg). The join is positional -- `ev_ids` is a counter generated by
    root2h5, not an identifier read from ROOT -- so it is verified, never assumed.
  * `E_ca` must not exceed the primary neutrino energy by more than the computed ionisation
    bound, which is the physical check no part of the reconstruction can see.

Usage (from project root):
    python data_manager/root2h5/create_energy_h5.py --ptype nue2_2020 \\
        --npz-dir data_manager/data/mc_energy_truth_interactions/nue2 \\
        [--out data_manager/data/h5datasets/baikal_mc_merged_energy_truth.h5] [--limit N]
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import h5py
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent / "energy_truth"))
from targets import R_LIMITS_M  # noqa: E402
from targets_vec import compute_targets  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
MAIN_H5 = ROOT / "data_manager/data/h5datasets/baikal_mc_merged.h5"
OUT_H5 = ROOT / "data_manager/data/h5datasets/baikal_mc_merged_energy_truth.h5"
SENTINEL = np.float32(-0.001)          # "muon born downstream of the reference point"
STRING_DIVISOR = 288                   # channels per cluster

# e_ref_class encodes the three cases of fMuonEnergy established in doc/mc_energy_truth.md §1
CLASS_ALIVE, CLASS_BORN_DOWNSTREAM, CLASS_DIED_UPSTREAM = 0, 1, 2

MUON_COLUMNS = ["theta_deg", "phi_deg", "x", "y", "z", "e_ref", "n_inter", "e_ref_class"]
TARGET_COLUMNS = (["E_ca", "s_ca", "b_impact", "s_first_int", "s_last_int", "s_death",
                   "sigma_target_min", "E_nu"]
                  + [f"E_dep_{int(r)}" for r in R_LIMITS_M]
                  + [f"L_path_{int(r)}" for r in R_LIMITS_M]
                  + [f"n_int_in_{int(r)}" for r in R_LIMITS_M])


def classify(e_ref: np.ndarray) -> np.ndarray:
    """Three cases of fMuonEnergy, doc/mc_energy_truth.md §1."""
    return np.where(e_ref > 0, CLASS_ALIVE,
                    np.where(e_ref.astype(np.float32) == SENTINEL,
                             CLASS_BORN_DOWNSTREAM, CLASS_DIED_UPSTREAM))


def _flat_ranges(starts: np.ndarray, lengths: np.ndarray) -> np.ndarray:
    """Concatenation of arange(start, start+length) without a Python loop."""
    total = int(lengths.sum())
    if total == 0:
        return np.zeros(0, dtype=np.int64)
    off = np.concatenate([[0], np.cumsum(lengths)]).astype(np.int64)
    return np.repeat(starts - off[:-1], lengths) + np.arange(total)


def build_part(g_main, npz, part: str, centres: np.ndarray) -> dict | None:
    """Compute every stored quantity for one part. Returns None if the part is absent."""
    if part not in g_main["ev_ids"]:
        return None
    ev_ids = g_main[f"ev_ids/{part}/data"][:]
    root_idx = np.array([int(x.decode().rsplit("_", 1)[1]) for x in ev_ids])
    mu_starts = g_main[f"muons_prty/mu_starts/{part}/data"][:].astype(np.int64)
    individ = g_main[f"muons_prty/individ/{part}/data"][:]
    ev_starts = g_main[f"raw/ev_starts/{part}/data"][:].astype(np.int64)
    # loaded eagerly: a lazy dataset reference decompresses on every row, which
    # dominated the runtime (3.9 ms per muon before the change)
    channels = g_main[f"raw/channels/{part}/data"][:]
    prime = g_main[f"prime_prty/{part}/data"][:]

    # Materialise the npz once. np.load on a compressed archive returns a lazy handle that
    # re-inflates the WHOLE array on every __getitem__, so touching npz["int_energy"] inside
    # the per-muon loop decompressed ~10^5 values per muon and dominated the runtime.
    trk_n_inter = npz["trk_n_inter"]
    trk_theta, trk_phi = npz["trk_theta"], npz["trk_phi"]
    trk_energy = npz["trk_energy"]
    int_energy = npz["int_energy"]
    int_block = npz["int_block"] if "int_block" in npz.files else np.zeros(len(int_energy))

    n_rows = len(root_idx)
    trk_off = np.concatenate([[0], np.cumsum(trk_n_inter)]).astype(np.int64)
    ev_trk_off = np.concatenate([[0], np.cumsum(npz["n_tracks"])]).astype(np.int64)
    refs = np.stack([npz["trk_x"], npz["trk_y"], npz["trk_z"]], axis=1)
    pts = np.stack([npz["int_x"], npz["int_y"], npz["int_z"]], axis=1)

    # cluster of each row = the one most of its hits belong to; the per-row bincount of the
    # loop becomes a single bincount over (row, cluster) pairs
    n_cl = len(centres)
    hit_cluster = channels[int(ev_starts[0]):int(ev_starts[-1])] // STRING_DIVISOR
    hit_row = np.repeat(np.arange(n_rows), np.diff(ev_starts))
    tally = np.bincount(hit_row * n_cl + hit_cluster,
                        minlength=n_rows * n_cl).reshape(n_rows, n_cl)
    cluster = tally.argmax(axis=1).astype(np.int16)

    # muons of each row: the main file's mu_starts gives the count, and the k-th muon of a row
    # is the k-th track of that row's ROOT entry. The last row is skipped when mu_starts has no
    # closing offset for it, exactly as the per-row loop did.
    n_mu_row = np.zeros(n_rows, dtype=np.int64)
    n_closed = max(0, min(n_rows, len(mu_starts) - 1))
    n_mu_row[:n_closed] = np.diff(mu_starts)[:n_closed]

    row_of_mu = np.repeat(np.arange(n_rows), n_mu_row)
    mu_off = np.concatenate([[0], np.cumsum(n_mu_row)]).astype(np.int64)
    k_in_row = np.arange(int(n_mu_row.sum())) - mu_off[row_of_mu]
    entry = root_idx[row_of_mu]
    trk = ev_trk_off[entry] + k_in_row
    beyond = trk >= ev_trk_off[entry + 1]
    if beyond.any():
        bad = int(np.argmax(beyond))
        raise RuntimeError(f"{part} row {row_of_mu[bad]}: muon {k_in_row[bad]} beyond "
                           f"ROOT entry {entry[bad]}")
    h5_rows = mu_starts[row_of_mu] + k_in_row       # row in muons_prty/individ

    n_inter_mu = trk_n_inter[trk].astype(np.int64)
    sel = _flat_ranges(trk_off[trk], n_inter_mu)     # interactions of the selected muons, flat
    centres_of_muon = centres[cluster[row_of_mu]]

    v = compute_targets(trk_theta[trk], trk_phi[trk], refs[trk],
                        trk_energy[trk].astype(np.float64), n_inter_mu,
                        pts[sel], int_energy[sel], centres_of_muon)

    targets = np.column_stack([v["E_ca"], v["s_ca"], v["b_impact"], v["s_first_int"],
                               v["s_last_int"], v["s_death"], v["sigma_target_min"],
                               prime[row_of_mu, 2],
                               v["E_dep"], v["L_path"], v["n_int_in"]])
    muon = np.column_stack([trk_theta[trk], trk_phi[trk], refs[trk],
                            trk_energy[trk], n_inter_mu, classify(trk_energy[trk])])

    return dict(
        ev_ids=ev_ids, mu_starts=mu_starts, cluster=cluster,
        int_starts=np.concatenate([[0], np.cumsum(n_inter_mu)]).astype(np.int64),
        interactions=np.column_stack([pts[sel], int_energy[sel],
                                      int_block[sel]]).astype(np.float32),
        muon=muon.astype(np.float32), targets=targets.astype(np.float32),
        _h5_rows=h5_rows, _np_rows=trk, _individ=individ,
        _npz={k: npz[k] for k in ("trk_x", "trk_y", "trk_z", "trk_energy", "trk_theta")},
    )


def verify(part: str, data: dict) -> None:
    """Abort on a broken join or a physically impossible energy."""
    individ, npz = data["_individ"], data["_npz"]
    h5_rows, np_rows = data["_h5_rows"], data["_np_rows"]
    if len(h5_rows) == 0:
        return
    for name, col, npz_key, tol in [("x", 2, "trk_x", 0.0), ("y", 3, "trk_y", 0.0),
                                    ("z", 4, "trk_z", 0.0), ("E", 6, "trk_energy", 0.0)]:
        bad = int((np.abs(individ[h5_rows, col] - npz[npz_key][np_rows]) > tol).sum())
        if bad:
            raise RuntimeError(f"{part}: {bad} muons disagree with muons_prty on {name} — "
                               f"the positional join is wrong, do not use this output")
    ang = np.abs(np.degrees(individ[h5_rows, 0]) - npz["trk_theta"][np_rows]).max()
    if ang > 1e-3:
        raise RuntimeError(f"{part}: theta differs by up to {ang:.2e} deg")

    cols = {c: i for i, c in enumerate(TARGET_COLUMNS)}
    t = data["targets"]
    e_ca, e_nu, floor = t[:, cols["E_ca"]], t[:, cols["E_nu"]], t[:, cols["sigma_target_min"]]
    finite = np.isfinite(e_ca) & (e_nu > 0)
    # beyond the ionisation bound the excess cannot be blamed on the extrapolation
    viol = finite & (e_ca > e_nu + floor + 1.0)
    if viol.mean() > 0.05:
        raise RuntimeError(f"{part}: {100*viol.mean():.1f}% of muons exceed E_nu beyond the "
                           f"ionisation bound — the propagation is wrong")


def write_part(out, ptype: str, part: str, data: dict) -> None:
    grp = out.require_group(ptype)
    for name, arr in [("ev_ids", data["ev_ids"]), ("mu_starts", data["mu_starts"]),
                      ("int_starts", data["int_starts"]), ("cluster", data["cluster"]),
                      ("interactions", data["interactions"]), ("muon", data["muon"]),
                      ("targets", data["targets"])]:
        path = f"{name}/{part}/data"
        if path in grp:
            del grp[path]
        grp.create_dataset(path, data=arr, compression="gzip", compression_opts=4)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ptype", required=True, help="e.g. nue2_2020")
    ap.add_argument("--npz-dir", required=True)
    ap.add_argument("--out", default=str(OUT_H5))
    ap.add_argument("--main-h5", default=str(MAIN_H5))
    ap.add_argument("--limit", type=int, default=0, help="0 = all parts")
    args = ap.parse_args()

    npz_files = sorted(Path(args.npz_dir).glob("*.npz"))
    if args.limit:
        npz_files = npz_files[:args.limit]
    print(f"{args.ptype}: {len(npz_files)} npz files -> {args.out}", flush=True)

    t0 = time.time()
    n_done = n_skip = n_mu = 0
    with h5py.File(args.main_h5, "r") as main, h5py.File(args.out, "a") as out:
        g_main = main[args.ptype]
        centres = g_main["clusters_centers/data"][:]
        out.attrs["target_columns"] = ",".join(TARGET_COLUMNS)
        out.attrs["muon_columns"] = ",".join(MUON_COLUMNS)
        out.attrs["interaction_columns"] = "x,y,z,energy_gev,block"
        out.attrs["r_limits_m"] = np.array(R_LIMITS_M)
        for i, path in enumerate(npz_files, 1):
            part = f"part_{path.stem}"
            npz = np.load(path)
            data = build_part(g_main, npz, part, centres)
            if data is None:
                n_skip += 1
                continue
            verify(part, data)
            write_part(out, args.ptype, part, data)
            n_done += 1
            n_mu += len(data["muon"])
            if i % 25 == 0 or i == len(npz_files):
                el = time.time() - t0
                print(f"  [{i}/{len(npz_files)}] parts={n_done} skipped={n_skip} "
                      f"muons={n_mu:,} {el/60:.1f} min", flush=True)

    print(f"\ndone: {n_done} parts, {n_mu:,} muons, {n_skip} skipped "
          f"({(time.time()-t0)/60:.1f} min)")


if __name__ == "__main__":
    main()
