# Configuration for root2h5.py
general:
  take_single_cluster: true
  take_clust_num: null
  split_multi: true
  shift_coords_to_cl_center: true
  center_times: true
  exclude_big_ts: true
  t_threshold: 1e5
  coords_are_same: false

multiprocessing:
  MAX_QUEUE_SIZE: 3
  NUM_WORKERS: 8

output:
  h5_name: "baikal_reco.h5"
  h5_prefix: "/home3/ivkhar/Baikal/data/h5s/"

input:
  particle: "nue2"
  MC_dir_path: "/home3/ivkhar/Baikal/data/initial_data/reco/nu2.100PeV/recMay23/all"

root_paths:
  data:
    - "Events/BEvent./BEvent.fPulses/BEvent.fPulses.fAmplitude"
    - "Events/BEvent./BEvent.fPulses/BEvent.fPulses.fTime"
    - "Events/MCEventMask./MCEventMask.BEventMask/MCEventMask.BEventMask.fOrigins/MCEventMask.BEventMask.fOrigins.fFlag"
    - "Events/BEvent./BEvent.fPulses/BEvent.fPulses.fChannelID"

  primary:
    - "Events/BMCEvent./BMCEvent.fPrimaryParticleTheta"
    - "Events/BMCEvent./BMCEvent.fPrimaryParticlePhi"
    - "Events/BMCEvent./BMCEvent.fPrimaryParticleEnergy"
    - "Events/BMCEvent./BMCEvent.fNucleonN"
    - "Events/BMCEvent./BMCEvent.fResponseMuonsN"
    - "Events/BMCEvent./BMCEvent.fEventWeight"

  resp_muons:
    - "Events/BMCEvent./BMCEvent.fTracks/BMCEvent.fTracks.fTheta"
    - "Events/BMCEvent./BMCEvent.fTracks/BMCEvent.fTracks.fPhi"
    - "Events/BMCEvent.fTracks.fX"
    - "Events/BMCEvent.fTracks.fY"
    - "Events/BMCEvent.fTracks.fZ"
    - "Events/BMCEvent./BMCEvent.fTracks/BMCEvent.fTracks.fDelay"
    - "Events/BMCEvent./BMCEvent.fTracks/BMCEvent.fTracks.fMuonEnergy"

  mu_scalar:
    - "Events/BMCEvent./BMCEvent.fFirstMuonTime"
    - "Events/BMCEvent./BMCEvent.fSumEnergyBundleReg"

  reco_ev:
    - "Events/BRecoMuon./BRecoMuon.fFuncValue"
    - "Events/BRecoMuon./BRecoMuon.fTimeChi2"
    - "Events/BRecoMuon./BRecoMuon.fChargeTerm"
    - "Events/BRecoMuon./BRecoMuon.fLLFit"
    - "Events/BRecoMuon./BRecoMuon.fNHits"
    - "Events/BRecoMuon./BRecoMuon.fNStrings"
    - "Events/BRecoMuon./BRecoMuon.fNOMs"
    - "Events/BRecoMuon./BRecoMuon.fThetaRec"
    - "Events/BRecoMuon./BRecoMuon.fPhiRec"
    - "Events/BRecoMuon./BRecoMuon.fSourceZenithRec"
    - "Events/BRecoMuon./BRecoMuon.fSourceAltitudeRec"
    - "Events/BRecoMuon./BRecoMuon.fSourceAzimuthRec"
    - "Events/BRecoMuon./BRecoMuon.fSourceDecliRec"
    - "Events/BRecoMuon./BRecoMuon.fTimeXYZRec"
    - "Events/BRecoMuon./BRecoMuon.fPathLength"

#  reco_om:
#    - "Events/BRecoMuon./BRecoMuon.fChanID"
#    - "Events/BRecoMuon./BRecoMuon.fRho"

  reco_vectors:
    - "Events/BRecoMuon./BRecoMuon.fXYZRec"
    - "Events/BRecoMuon./BRecoMuon.fDirectionRec"

  reco_mask: "Events/RecoMuonMask./RecoMuonMask.fOrigins/RecoMuonMask.fOrigins.fFlag"

  geometry: "Events/BGeomTel./BGeomTel.BGeomTel/BGeomTel.BGeomTel.fOMs/BGeomTel.BGeomTel.fOMs.fPosition"
