apply_add_gauss: false
apply_lr_decay: true
apply_mult_gauss: false
checkpoint_cutting: 1.0
cutting: 1.0
early_stop_params:
  min_delta: 1.0e-06
  mode: max
  monitor: val_Expos_on_Suppr
  patience: 20
g_add_stds: null
loss_kwargs:
  gamma_mu: 2.0
  gamma_nu: 2.0
  w_mu: 1.0
  w_nu: 1.0
lr: 0.0005 <keras.src.optimizers.schedules.learning_rate_schedule.ExponentialDecay
  object at 0x7f6f96eec9d0>
lr_decay: 0.02
metrics: '[''accuracy'', <NNBlock.nn.metrics.Expos_on_Suppr object at 0x7f6f97005010>]'
num_of_epochs: 200
q_noise_fraction: 0.1
set_up_Q_lim: true
start: 0
up_Q_lim: 100.0
verbose: false
verbose_cutting: 50.0
