apply_lr_decay: false
checkpoint_cutting: 1.0
cutting: 1.0
early_stop_params:
  min_delta: 1.0e-06
  mode: min
  monitor: val_loss_E
  patience: 20
loss_E_name: MyLoss
loss_sigma_name: null
lr: 0.0002 0.0002
lr_decay: 0.002
lr_sigma: 0.0002 0.0002 0.0002
metrics: '[<NNBlock.nn.metrics.nlogE_MAE object at 0x7f3d981845b0>, <NNBlock.nn.metrics.nSigmaAbsMAE
  object at 0x7f3d9815f880>]'
num_of_epochs: 300
optimizer: <class 'keras.optimizers.optimizer_experimental.adam.Adam'>
verbose: false
verbose_cutting: 50.0
weighted_metrics: '[<NNBlock.nn.metrics.nlogE_MAE object at 0x7f3d803f52d0>, <NNBlock.nn.metrics.nSigmaAbsMAE
  object at 0x7f3da010f220>]'
